# Generated by Django 4.2.11 on 2024-03-18 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_featured_image_alter_course_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(null=True, verbose_name='Course Date'),
        ),
    ]
