# Generated by Django 4.2.11 on 2024-03-18 20:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Course Date'),
        ),
    ]
