# Generated by Django 4.2.11 on 2024-03-21 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
