# Generated by Django 4.2.11 on 2024-03-21 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_comment_reply_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='reply_body',
        ),
    ]
