# Generated by Django 4.2.11 on 2024-03-21 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_commentreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
