# Generated by Django 4.2.11 on 2024-03-23 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_reportedcomment_commentrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportedcomment',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='reportedcomment',
            name='reporter',
        ),
        migrations.DeleteModel(
            name='CommentRating',
        ),
        migrations.DeleteModel(
            name='ReportedComment',
        ),
    ]
